org.gradle.jvmargs=-Xmx2048M

#minecraft
minecraft_version=1.21.1
minecraft_version_range=1.21.1
enabled_platforms=fabric,neoforge

#mod
mod_name=MC Story Mode Armors
archives_base_name=mcsa
mod_version=5.0.0
maven_group=dev.timefall

description=Brings the armors from Minecraft Story Mode to Minecraft Java.
mod_author=chronosacaria
credits=chronosacaria
license=Timefall Development License 1.2

#loaders
fabric_api_version=0.116.17+1.21.1
fabric_loader_version=0.19.5

neoforge_version=21.1.235
neoforge_loader_version_range=21.0.0-beta

#yarn version
yarn_mappings=3

#dependencies
fzzy_config_version=0.7.6+1.21



mod_publish_plugin_version=0.3.4

architectury_plugin_version=3.4-SNAPSHOT
architectury_loom_version=1.11-SNAPSHOT











# Done to increase the memory available to gradle.
#org.gradle.jvmargs=-Xmx1G
#org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop/
#minecraft_version=1.21
#yarn_mappings=1.21+build.9
#fabric_loader_version=0.15.11

# Mod Properties
#mod_version=10.0.0
#maven_group=dev.timefall
#archives_base_name=mcdw

# Dependencies
# check this on https://fabricmc.net/develop/
#fabricKotlinVersion = 1.10.18+kotlin.1.9.22
#fabric_version=0.100.7+1.21
#fzzy_config=0.3.5+1.21

# Compatibility
#clumps_version=18.0.0.1
#ranged_weapon_api_version=1.1.1+1.20.1